# SLAM mode
mode: "online_async"  # Online SLAM mode for real-time mapping

# Map settings
resolution: 0.05  # Map resolution in meters per cell
map_update_interval: 2.0  # How often to update the map (seconds)
map_publish_period: 1.0  # How often the map is published (seconds)

# Lidar configuration (matches URDF lidar sensor settings)
laser_min_range: 0.3  # Minimum valid lidar range (URDF: 0.3 meters)
laser_max_range: 12.0  # Maximum valid lidar range (URDF: 12 meters)

# Transform settings
transform_publish_period: 0.05  # Frequency to publish TFs
map_frame: "map"  # Frame for the map
odom_frame: "odom"  # Odometry frame
base_frame: "base_link"  # Robot’s base frame

# Sensor fusion and optimization
use_scan_matching: true  # Use scan matching to improve accuracy
use_odometry: true  # Use odometry data from Gazebo's differential drive
provide_odom_frame: true  # Allow SLAM to provide the odom frame
publish_tf: true  # Ensure SLAM publishes the necessary transforms

# Loop closure settings (improve map consistency)
use_loop_closure: true  # Enable loop closure detection
check_for_loop_closures: true  # Actively check for loop closures
optimization_frequency: 1.0  # Frequency to optimize the map (Hz)

# Simulation settings
use_sim_time: true  # Use simulation time from Gazebo
